import * as stylex from '@stylexjs/stylex'

const progressSweep = stylex.keyframes({
  from: { transform: 'translateX(-120%)' },
  to: { transform: 'translateX(320%)' },
})

export const deviceGalleryStyles = stylex.create({
  root: {
    display: 'grid',
    width: '100%',
    maxWidth: '100%',
    minWidth: 0,
    boxSizing: 'border-box',
    gap: 12,
    borderTopColor: 'var(--ui-divider)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingBlock: 16,
    paddingInline: 18,
    backgroundColor: 'var(--ui-surface)',
  },
  headingRow: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  headingCopy: {
    flex: '1 1 240px',
    minWidth: 0,
  },
  heading: {
    margin: 0,
    color: 'var(--ui-text)',
    fontSize: 14,
    fontWeight: 650,
    letterSpacing: '-0.005em',
    lineHeight: '19px',
  },
  label: {
    color: 'var(--ui-text)',
    fontSize: 13,
    fontWeight: 550,
    lineHeight: '18px',
  },
  description: {
    margin: 0,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
    lineHeight: '16px',
    overflowWrap: 'anywhere',
  },
  compactButton: {
    minHeight: 30,
    gap: 6,
    borderRadius: 7,
    paddingInline: 10,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  connectionRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(180px, 260px) minmax(0, 1fr)',
    alignItems: 'center',
    gap: 12,
  },
  address: {
    width: '100%',
  },
  addressHint: {
    color: 'var(--ui-text-muted)',
    fontSize: 11,
    lineHeight: '16px',
  },
  metrics: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    color: 'var(--ui-text-muted)',
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: 10,
    lineHeight: '15px',
    overflowWrap: 'anywhere',
  },
  uploadGrid: {
    'display': 'grid',
    'minWidth': 0,
    'gridTemplateColumns': 'minmax(0, 1.2fr) minmax(150px, 0.8fr)',
    'gap': 14,
    'alignItems': 'stretch',
    '@media (max-width: 640px)': {
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  preview: {
    overflow: 'hidden',
    minWidth: 0,
    minHeight: 170,
    borderColor: 'var(--ui-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    backgroundColor: '#fffdf8',
  },
  emptyPreview: {
    display: 'grid',
    height: '100%',
    minHeight: 170,
    placeContent: 'center',
    justifyItems: 'center',
    gap: 7,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
  },
  cropEditor: {
    display: 'grid',
    minWidth: 0,
    gap: 8,
    padding: 8,
  },
  cropViewport: {
    position: 'relative',
    width: '100%',
    aspectRatio: '4 / 3',
    overflow: 'hidden',
    borderRadius: 6,
    backgroundColor: '#ede9df',
    cursor: {
      'default': 'grab',
      ':active': 'grabbing',
    },
    outlineColor: {
      'default': 'transparent',
      ':focus-visible': 'var(--ui-focus-ring)',
    },
    outlineOffset: 2,
    outlineStyle: 'solid',
    outlineWidth: 2,
    touchAction: 'none',
    userSelect: 'none',
  },
  cropCanvas: {
    position: 'absolute',
    inset: 0,
    display: 'block',
    width: '100%',
    height: '100%',
    pointerEvents: 'none',
    userSelect: 'none',
  },
  cropGuide: {
    position: 'absolute',
    inset: 0,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: 'inset 0 0 0 1px rgba(20, 18, 15, 0.28)',
    pointerEvents: 'none',
  },
  cropToolbar: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  zoomControl: {
    display: 'grid',
    minWidth: 0,
    flex: '1 1 auto',
    gridTemplateColumns: 'auto minmax(80px, 1fr)',
    alignItems: 'center',
    gap: 8,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
  },
  zoomSlider: {
    width: '100%',
    minWidth: 0,
    accentColor: 'var(--ui-text)',
  },
  cropHint: {
    margin: 0,
    color: 'var(--ui-text-muted)',
    fontSize: 10,
    lineHeight: '14px',
  },
  canvas: {
    display: 'block',
    width: '100%',
    height: 'auto',
    imageRendering: 'auto',
  },
  uploadControls: {
    display: 'grid',
    minWidth: 0,
    alignContent: 'start',
    gap: 8,
  },
  convertedPreview: {
    display: 'grid',
    minWidth: 0,
    gap: 5,
    overflow: 'hidden',
    borderColor: 'var(--ui-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    padding: 6,
    backgroundColor: '#fffdf8',
  },
  previewLabel: {
    color: 'var(--ui-text-muted)',
    fontSize: 10,
    lineHeight: '14px',
  },
  progressGroup: {
    display: 'grid',
    minWidth: 0,
    gap: 6,
  },
  progressCopy: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
    lineHeight: '15px',
  },
  progressTrack: {
    position: 'relative',
    width: '100%',
    height: 5,
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: 'var(--ui-divider)',
  },
  progressValue: {
    position: 'absolute',
    inset: 0,
    borderRadius: 'inherit',
    backgroundColor: 'var(--ui-text)',
    transformOrigin: 'left center',
    transition: 'transform 120ms ease-out',
  },
  progressIndeterminate: {
    'position': 'absolute',
    'insetBlock': 0,
    'left': 0,
    'width': '28%',
    'borderRadius': 'inherit',
    'backgroundColor': 'var(--ui-text)',
    'animationDuration': '1.2s',
    'animationIterationCount': 'infinite',
    'animationName': progressSweep,
    'animationTimingFunction': 'ease-in-out',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
      transform: 'translateX(128%)',
    },
  },
  control: {
    width: '100%',
    minWidth: 0,
  },
  fileButton: {
    position: 'relative',
    display: 'inline-flex',
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: '100%',
    boxSizing: 'border-box',
    overflow: 'hidden',
    borderColor: 'var(--ui-field-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingInline: 10,
    backgroundColor: {
      'default': 'var(--ui-field-background)',
      ':hover': 'var(--ui-control-hover)',
      ':active': 'var(--ui-control-pressed)',
    },
    color: 'var(--ui-text)',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  fileInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
  slideshowRow: {
    'display': 'grid',
    'minWidth': 0,
    'gridTemplateColumns': 'minmax(0, 1fr) minmax(140px, 210px)',
    'alignItems': 'center',
    'gap': 14,
    'borderTopColor': 'var(--ui-divider)',
    'borderTopStyle': 'solid',
    'borderTopWidth': 1,
    'paddingTop': 12,
    '@media (max-width: 560px)': {
      alignItems: 'stretch',
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  slideshowCopy: {
    minWidth: 0,
  },
  assetList: {
    display: 'grid',
    minWidth: 0,
    borderTopColor: 'var(--ui-divider)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  emptyList: {
    margin: 0,
    paddingBlock: 18,
    color: 'var(--ui-text-muted)',
    fontSize: 12,
    textAlign: 'center',
  },
  assetRow: {
    'display': 'grid',
    'minWidth': 0,
    'minHeight': 48,
    'gridTemplateColumns': 'minmax(0, 1fr) auto',
    'alignItems': 'center',
    'gap': 12,
    'borderBottomColor': 'var(--ui-divider)',
    'borderBottomStyle': 'solid',
    'borderBottomWidth': 1,
    'paddingBlock': 7,
    '@media (max-width: 440px)': {
      alignItems: 'stretch',
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  assetCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 1,
  },
  assetName: {
    overflow: 'hidden',
    color: 'var(--ui-text)',
    fontSize: 12,
    fontWeight: 550,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  assetMeta: {
    color: 'var(--ui-text-muted)',
    fontSize: 10,
    lineHeight: '15px',
  },
  assetActions: {
    display: 'flex',
    minWidth: 0,
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
  },
  iconButton: {
    minWidth: 28,
    minHeight: 28,
    gap: 4,
    borderRadius: 6,
    paddingInline: 7,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
  },
})
